# Generated by Django 4.2.1 on 2023-06-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='target_user',
            new_name='followed_user',
        ),
    ]
