# Generated by Django 4.2.1 on 2023-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='images/'),
        ),
    ]
